name: scylla-cluster
services:
  scylla-node1:
    container_name: scylla-node1
    hostname: scylla-node1
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M
    volumes:
      - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./config/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
      - "./data/mutant-data.txt:/mutant-data.txt"
    ports:
      - 9100:9100 # Node Exporter
      - 9180:9180 # Scylla Metrics
    networks:
      vnet:

  scylla-node2:
    container_name: scylla-node2
    hostname: scylla-node2
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M 
    volumes:
      - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./config/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - 9101:9100 # Node Exporter
      - 9181:9180 # Scylla Metrics
    depends_on:
      - scylla-node1
    networks:
      vnet:

  scylla-node3:
    container_name: scylla-node3
    hostname: scylla-node3
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M
    volumes:
      - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./config/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - 9102:9100 # Node Exporter
      - 9182:9180 # Scylla Metrics
    depends_on:
      - scylla-node1
      - scylla-node2
    networks:
      vnet:

networks:
  vnet:
    driver: bridge