version: "3.7"

services:
  scylla-manager:
    image: scylladb/scylla-manager
    # volumes:
      # - ./config/scylla-manager.yaml:/etc/scylla-manager/scylla-manager.yaml
    networks:
      public:
    depends_on:
      - scylla-manager-db

  scylla-manager-db:
    image: scylladb/scylla
    volumes:
      - scylla_manager_db_data:/var/lib/scylla
    networks:
      public:
        ipv4_address: 192.168.100.200
    command: --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0

  scylla:
    build:
      context: .
    image: scylladb/scylla-with-agent
    volumes:
      - scylla_data:/var/lib/scylla
      # - ./config/scylla-manager-agent.yaml:/etc/scylla-manager-agent/scylla-manager-agent.yaml
      # - ./config/scylla-manager-agent.conf:/etc/supervisord.conf.d/scylla-manager-agent.conf
    networks:
      public:
        ipv4_address: 192.168.100.100
    command: --smp 1 --memory 1G

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    networks:
      public:
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

volumes:
  minio_data:
  scylla_data:
  scylla_manager_db_data:

networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24