# https://opensource.docs.scylladb.com/stable/getting-started/logging.html
# Listed below are a few useful examples.

# get logs generated by the “scylla” user:
journalctl _UID=`id -u scylla`

# get logs generated by the “scylla” command:
journalctl _COMM=scylla

# filter only Scylla logs by priority:
journalctl _COMM=scylla -p err..emerg
journalctl _COMM=scylla -p warning

# filter only Scylla logs by date:
journalctl _COMM=scylla --since="2013-3-16 23:59:59"
journalctl _COMM=scylla --since "2015-01-10" --until "2015-01-11 03:00"
journalctl _COMM=scylla --since yesterday

# filter only Scylla logs since last server boot:
journalctl _COMM=scylla -b